<?php

return [
    'displayable_types' =>
    [
        'plug',
        'light',
        'thermostat',
        'camera',
        'speaker',
        'lock',
        'sensor',
        'tv',
        'vacuum',
        'doorbell',
        'garage_door',
        'sprinkler',
        'fridge',
        'oven',
        'washer',
        'dryer',
        'fan',
        'humidifier',
        'dehumidifier',
        'air_conditioner',
        'heater',
        'blinds',
        'curtains',
        'projector',
        'coffee_maker',
        'microwave',
        'robot_vacuum',
        'switch',
        'outlet',
    ],

    'type_display_names' =>
    [
        'plug' => 'Plugs',
        'light' => 'Lights',
        'thermostat' => 'Thermostat',
        'camera' => 'Cameras',
        'speaker' => 'Speaker',
        'lock' => 'Lock',
        'sensor' => 'Sensors',
        'tv' => 'TV',
        'vacuum' => 'Vacuum',
        'doorbell' => 'Doorbell',
        'garage_door' => 'Garage Door',
        'sprinkler' => 'Sprinkler',
        'fridge' => 'Fridge',
        'oven' => 'Oven',
        'washer' => 'Washer',
        'dryer' => 'Dryer',
        'fan' => 'Fan',
        'humidifier' => 'Humidifier',
        'dehumidifier' => 'Dehumidifier',
        'air_conditioner' => 'Air Conditioner',
        'heater' => 'Heater',
        'blinds' => 'Blinds',
        'curtains' => 'Curtains',
        'projector' => 'Projector',
        'coffee_maker' => 'Coffee Maker',
        'microwave' => 'Microwave',
        'switch' => 'Plugs',
        'outlet' => 'Outlet',
    ],
];
